# Generated by Django 5.0.4 on 2024-04-13 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="inventory", name="store",),
        migrations.AddField(
            model_name="product",
            name="store",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="companies.store",
            ),
            preserve_default=False,
        ),
    ]
