# Generated by Django 5.0.4 on 2024-04-10 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="store",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="store",
            name="manager",
            field=models.ForeignKey(
                limit_choices_to={"role": "STORE_MANAGER"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stores",
                to="accounts.user",
            ),
        ),
    ]
