# Generated by Django 5.0.4 on 2024-04-14 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0003_product_total_sold_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
